codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  ignore:
    - Scripts/*
    - Vendor/*
    - Pods/*
    - FBSnapshotsViewerTests/*
  status:
    patch: false
    changes: false
    project:
      default:
        target: 70
