require 'kramdown'

fastlane_version "2.21.0"
default_platform :osx

platform :mac do
  GITHUB_REMOTE = "origin"
  RELEASE_BRANCH = "master"
  GITHUB_REPOSITORY = "Antondomashnev/FBSnapshotsViewer"
  SPECS_REPOSITORY_SOURCE = "git@github.com:CocoaPods/Specs.git"

  before_all do
    bundle_install
  end

  desc "Sanity check for the fastfile issues"
  lane :sanity_check do
    UI.message "Compiling Fastfile to check if the syntax if valid or not"
  end

  desc "Create a new build of FBSnapshotsViewer"
  lane :build_app do
    puts "Building an app into /bin folder..."
    gym(
      workspace: "FBSnapshotsViewer.xcworkspace",
      scheme: "FBSnapshotsViewer",
      configuration: "Release",
      derived_data_path: "#{ENV["BUILD_DIR"]}/tmp/",
      output_directory: "bin/",
      clean: true
    )
  end

  desc "Run test of FBSnapshotsViewer"
  lane :test do
    scan(
      workspace: "FBSnapshotsViewer.xcworkspace",
      scheme: "FBSnapshotsViewer",
      clean: true,
      code_coverage: true,
      output_types: "junit"
    )
  end

  desc "Release a new version of the FBSnapshotsViewer. Uploading a new release to a GitHub and CocoaPods trunk"
  desc "Before doing so don't forget to move the next version of Changelog to released"
  lane :release do
    ensure_git_status_clean
    test
    build_app

    release_human_version = project_get_human_version
    release_machine_version = project_get_machine_version

    git_add_or_update_tag(
      tag_name: release_human_version
    )

    github_set_or_update_release(
      release_name: release_human_version,
      repository_name: GITHUB_REPOSITORY,
      description: "",
      tag_name: release_human_version,
      upload_assets: github_create_release_assets(release_version: release_human_version),
      api_token: ENV["FB_SNAPSHOTS_VIEWER_GITHUB_API_TOKEN"]
    )
  end

  ##### INTENDED TO BE PRIVATE #####

  desc "Updates sparkle RSS file"
  desc "####Options"
  desc "* **`machine_version`** - sparkle's version"
  desc "* **`human_version`** - sparkle's human visible version"
  lane :sparkle_add_version do |options|
    machine_version = options[:machine_version]
    human_version = options[:human_version]
    app_download_url = "https://github.com/Antondomashnev/FBSnapshotsViewer/releases/download/#{human_version}/FBSnapshotsViewer-#{human_version}.app.zip"
  end

  desc "Returns the changelog for the given version from CHANGELOG.md"
  desc "####Options"
  desc "* **`changelog_path`** - path to the changelog file"
  desc "* **`version`** - version to get changelog for"
  desc "* **`convert_to_html`** - whether the changelog result must be converted into HTML"
  lane :project_version_changelog do |options|
    given_version = options[:version]
    changelog_path = options[:changelog_path]
    convert_to_html = options[:convert_to_html].nil? ? false : options[:convert_to_html]
    markdown_version_header_prefix = "###"
    markdown_changelog_entry_prefix = "*"
    given_version_changelog_entries = []
    reading_given_version_changelog = false
    File.readlines(changelog_path).each do |line|
      if line.start_with? "#{markdown_version_header_prefix} #{given_version}"
        reading_given_version_changelog = true
      elsif line.start_with? "#{markdown_version_header_prefix}"
        next unless reading_given_version_changelog
        reading_given_version_changelog = false if reading_given_version_changelog
      elsif reading_given_version_changelog && line.start_with?(markdown_changelog_entry_prefix)
        given_version_changelog_entries << line
      else
        next
      end
    end

    result_changelog_string = given_version_changelog_entries.join("\n")
    UI.message "Changelog for the version #{given_version} is #{result_changelog_string}"

    if convert_to_html
      Kramdown::Document.new(result_changelog_string).to_html
    else
      result_changelog_string
    end
  end

  desc "Returns the human readable project version"
  lane :project_get_human_version do
    human_version = get_info_plist_value(
      key: "CFBundleShortVersionString",
      path: "./FBSnapshotsViewer/Info.plist"
    )
    UI.message "Project's human version: #{human_version}"
    human_version
  end

  desc "Returns the machine project version"
  lane :project_get_machine_version do
    machine_version = get_info_plist_value(
      key: "CFBundleVersion",
      path: "./FBSnapshotsViewer/Info.plist"
    )
    UI.message "Project's machine version: #{human_version}"
    machine_version
  end

  desc "Creates or updates github release."
  desc "####Options"
  desc "* **`release_name`** - release name"
  desc "* **`description`** - release description"
  desc "* **`repository_name`** - repositiry name in format 'Antondomashnev/FBSnapshotsViewer'"
  desc "* **`tag_name`** - tag name"
  desc "* **`api_token`** - github api token"
  desc "* **`upload_assets`** - array of paths to files to be uploaded and attached to the release"
  lane :github_set_or_update_release do |options|
    release_name = options[:release_name]
    description = options[:description]
    repository_name = options[:repository_name]
    tag_name = options[:tag_name]
    api_token = options[:api_token]
    upload_assets = options[:upload_assets]

    release = get_github_release(
      url: repository_name,
      version: release_name,
      api_token: api_token
    )

    if release != nil
      edit_github_release(
        repository_name: repository_name,
        id: release['id'].to_s,
        description: description,
        tag_name: tag_name,
        name: release_name,
        api_token: api_token,
        upload_assets: upload_assets
      )
    else
      set_github_release(
        repository_name: repository_name,
        api_token: api_token,
        name: release_name,
        tag_name: tag_name,
        description: description,
        upload_assets: upload_assets,
        is_draft: false,
        is_prerelease: false
      )
    end
  end

  desc "Create or update tag with the given name."
  desc "####Options"
  desc "* **`tag_name`** - tag name to be used"
  lane :git_add_or_update_tag do |options|
    remote = GITHUB_REMOTE
    branch = RELEASE_BRANCH

    branch_exist = git_branch_exists_on_remote(
      remote: remote,
      branch: branch
    )

    sh("git pull #{remote} #{branch} --tags") if branch_exist.to_i

    tag_name = options[:tag_name]
    if git_tag_exists(tag: tag_name)
      sh("git tag #{tag_name} -d")
      sh("git push #{remote} :refs/tags/#{tag_name}")
    end

    sh("git tag #{tag_name}")
    sh("git push #{remote} --tags")
  end

  desc "Create assets to be uploaded as a github release"
  desc "####Options"
  desc "* **`release_version`** - releave version to be used as a part of name of asset"
  lane :github_create_release_assets do |options|
    release_version = options[:release_version]
    [github_create_app_release_assets(release_version: release_version)]
  end

  desc "Create app asset to be uploaded as a github release"
  desc "####Options"
  desc "* **`release_version`** - releave version to be used as a part of name of asset"
  desc "####Return"
  desc "Path to the asset"
  lane :github_create_app_release_assets do |options|
    require 'fileutils'
    release_version = options[:release_version]
    app_path = "./bin/FBSnapshotsViewer-#{release_version}.app"
    Dir.chdir(File.expand_path("./bin", "..")) do
      old_name = "FBSnapshotsViewer.app"
      new_name = "FBSnapshotsViewer-#{release_version}.app"
      FileUtils.rm_rf(new_name) if File.exist?(new_name)
      File.rename(old_name, new_name)
    end
    app_path
  end

  desc "Checks if the given 'branch' exists on the 'remote'."
  desc "####Options"
  desc "* **`remote`** - git remote in format git@github.com:conichiGMBH/ios-fastlane.git"
  desc "* **`branch`** - branch name"
  desc ""
  lane :git_branch_exists_on_remote do |options|
    remote = options[:remote]
    branch = options[:branch]
    sh("git ls-remote --heads #{remote} #{branch} | wc -l")
  end
end
